// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wshlv1.API.Data;

namespace wshlv1.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("wshlv1.API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AwayGoals");

                    b.Property<int>("AwayTeamId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HomeGoals");

                    b.Property<int>("HomeTeamId");

                    b.Property<int>("VictorId");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("wshlv1.API.Models.Goalie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<double>("GAA");

                    b.Property<int>("GamesPlayed");

                    b.Property<int>("GamesWon");

                    b.Property<string>("LastName");

                    b.Property<int>("Number");

                    b.Property<string>("PhotoUrl");

                    b.Property<double>("SavePercentage");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Goalies");
                });

            modelBuilder.Entity("wshlv1.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Assists");

                    b.Property<string>("Bio");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<int>("GamesPlayed");

                    b.Property<int>("Goals");

                    b.Property<string>("LastName");

                    b.Property<int>("Number");

                    b.Property<int>("PIMs");

                    b.Property<string>("PhotoUrl");

                    b.Property<int>("PlusMinus");

                    b.Property<int>("Points");

                    b.Property<char>("Position");

                    b.Property<int>("SOG");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("wshlv1.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GamesPlayed");

                    b.Property<int>("GoalsAgainst");

                    b.Property<int>("GoalsFor");

                    b.Property<int>("Losses");

                    b.Property<string>("Name");

                    b.Property<int>("OTL");

                    b.Property<int>("OTW");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("Points");

                    b.Property<string>("Username");

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("wshlv1.API.Models.Game", b =>
                {
                    b.HasOne("wshlv1.API.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("wshlv1.API.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("wshlv1.API.Models.Goalie", b =>
                {
                    b.HasOne("wshlv1.API.Models.Team", "Team")
                        .WithMany("Goalies")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("wshlv1.API.Models.Player", b =>
                {
                    b.HasOne("wshlv1.API.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
